FROM node:10-alpine

ENV appDir /appfinder-server
WORKDIR ${appDir}

COPY package*.json ./

RUN apk add --update python #needed for sqlite3
RUN apk add --update vim
RUN apk add --update sqlite
RUN npm install --only=production

# Bundle app source
COPY . .

EXPOSE 3000

RUN npm install --unsafe-perm=true sqlite3 -g #w/o unsafe-perm there're permission issues
RUN npm install pm2 -g
